export const academyCourses = [
  {
    id: 1,
    courseType: "FULL TIME COURSE",
    certificateType: "NATIONAL CERTIFICATE",
    certificateName:
      "NATIONAL CERTIFICATE: CLOTHING DESIGN DEVELOPMENT, ENTREPRENEURSHIP & RETAIL",
    duration: "2 Years",
    fees: "R18 700 (Year 1) and R19 900 (Year 2)",
    discountInfo:
      "7% discount is issued if fees are paid upfront in full. 5% discount is issued if full fees are paid by June.",
    times: "Monday - Thurs 8am-4pm  and Friday 8am-12pm",
    curriculum: [
      "Design Aesthetics",
      "Clothing Technology",
      "Fashion Merchandising, Marketing and Media",
      "Fashion Retail Management",
      "Entrepreneurial Studies",
      "Lifestyle Studies",
      "Community Engagement",
      "Fashion Value Chain Link-Fashion and Textile Design",
      "Fashion Value Chain Link-Fashion Retail",
      "Fashion Value Chain Link-Manufacturing and Distribution",
      "Work Integrated Learning/In Service Training",
      "Creative Output-Design Collection for Fashion Week/s (end of year 2)"
    ],
    technicalSamples: []
  },
  {
    id: 2,
    courseType: "FULL TIME COURSE",
    certificateType: "NATIONAL CERTIFICATE",
    certificateName:
      "NATIONAL CERTIFICATE: CLOTHING TECHNOLOGY AND ENTREPRENEURSHIP",
    duration: "1 Years",
    fees: "R11 700",
    discountInfo:
      "7% discount is issued if fees are paid upfront in full. 5% discount is issued if full fees are paid by June.",
    times: "Monday - Thurs 8am-4pm and Friday 8am-12pm",
    curriculum: [
      "Design Aesthetics",
      "Fashion History",
      "Textiles 101",
      "Clothing Technology",
      "Entrepreneurial Studies",
      "Lifestyle Studies",
      "Community Engagement",
      "Creative Output-Design Collection for Fashion Week/s (end of year 1)"
    ],
    technicalSamples: []
  },
  {
    id: 3,
    courseType: "SHORT COURSE",
    certificateType: "SKILLS PROGRAMME CERTIFICATE",
    certificateName:
      "SKILLS PROGRAMME CERTIFICATE: APPLIED DESIGN",
    duration: "12 weeks",
    fees: "R3 800 ( incl. reg fees of R1 900)",
    discountInfo: "",
    times: "Saturdays only 8am-12pm | 12pm-4pm",
    curriculum: [
      "Costing",
      "Range Build",
      "Marketing",
      "SETA Business Modules",
      "Pattern Plan",
      "Garment Mock up",
      "Fabric Orientation",
      "Quality",
      "Creative Direction",
      "Product Categories",
      "Design (Technical Drawings, Tech Specs, Storyboards, Spec Sheets, Mood Boards and Pin Boards)",
      "Fashion History"
    ],
    technicalSamples: []
  },
  {
    id: 4,
    courseType: "SHORT COURSE",
    certificateType: "SKILLS PROGRAMME CERTIFICATE",
    certificateName:
      "SKILLS PROGRAMME CERTIFICATE: BASIC PATTERN SKILLS AND DESIGN",
    duration: "12 weeks",
    fees: "R3 800 ( incl. reg fees of R1 900)",
    discountInfo: "",
    times: "Saturdays only 8am-12pm | 12pm-4pm",
    curriculum: [
      "Garment finishing’s, facings, linings and interlinings",
      "Dart positionings, style lines and variations",
      "Implementation of calculations for Basic Blocks",
      "Half Scale Blocks and Seam allowance variations and functions",
      "Placing and rating of fabric, Marking of pattern pieces",
      "Pinning and cutting of fabric and Basic pockets",
      "Female Block drafting for the Bodice, Skirt, Dress and Basic Sleeve",
      "Mock up",
      "Pattern Theory: Definition and Terminology",
      "Brief History and principles of pattern design",
      "Textiles (Authentic and Synthetics in relation to grain variation)",
      "Figure Assessment and Measurements",
      "Tools Pattern Design Equipment",
      "Importance of a grain and identifying the grain on fabric and Analysis of silhouettes",
      "Factors such as fabric quality, shape and line."
    ],
    technicalSamples: []
  },
  {
    id: 5,
    courseType: "SHORT COURSE",
    certificateType: "SKILLS PROGRAMME CERTIFICATE",
    certificateName:
      "SKILLS PROGRAMME CERTIFICATE: ADVANCED PATTERN SKILLS AND DESIGN",
    duration: "12 weeks",
    fees: "R3 800 ( incl. reg fees of R1 900)",
    discountInfo: "",
    times: "Saturdays only 8am-12pm | 12pm-4pm",
    curriculum: [
      "Garment finishing’s, facings, linings and interlinings",
      "Dart positionings, style lines and variations",
      "Implementation of calculations for Basic Blocks",
      "Half Scale Blocks and Seam allowance variations and functions",
      "Placing and rating of fabric, Marking of pattern pieces",
      "Pinning and cutting of fabric and Basic pockets",
      "Female Block drafting for the Bodice, Skirt, Dress and Basic Sleeve",
      "Mock up",
      "Pattern Theory: Definition and Terminology",
      "Brief History and principles of pattern design",
      "Textiles (Authentic and Synthetics in relation to grain variation)",
      "Figure Assessment and Measurements",
      "Tools Pattern Design Equipment",
      "Importance of a grain and identifying the grain on fabric and Analysis of silhouettes",
      "Factors such as fabric quality, shape and line."
    ],
    technicalSamples: []
  },
  {
    id: 6,
    courseType: "SHORT COURSE",
    certificateType: "SKILLS PROGRAMME CERTIFICATE",
    certificateName:
      "SKILLS PROGRAMME CERTIFICATE :BASIC GARMENT CONSTRUCTION AND TECHNOLOGY",
    duration: "12 weeks",
    fees: "R3 800 ( incl. reg fees of R1 900)",
    discountInfo: "",
    times: "Saturdays only 8am-12pm | 12pm-4pm",
    curriculum: [
      "Machine theory",
      "Terminology and visual knowledge of threading a single needle lockstitch machine and or over locker (demonstration by mentor)",
      "General rules for machine care",
      "Variants of machines in the industry and sewing equipment and attachments used for this program",
      "Stitch types",
      "Definition and relevance to the apparel industry",
      "Classification of Stitches",
      "Seams",
      "Definition and purpose",
      "Procedure and variations of seams",
      "Techniques (Demonstration by mentor)",
      "Interlining, lining, facings",
      "Technical sampling and Seam samples",
      "Closure samples and Variations of hemming",
      "Theory and Thread Path",
      "Procedures and functions of pressing",
      "Garment replication exercises",
      "Placing, rating and cutting of fabric correctly",
      "Bodice with a single style incorporated",
      "Skirt with functional pockets and closure",
      "Dress with darts and short sleeves",
      "Rating, Placing, Cutting, Quality and Labelling",
      "Production Theory such as commonly used machinery in apparel production",
      "Systematically know the correct method of needle thread path on a single lock stitch machine with sound knowledge on bobbin case bobbin winding, threading and insertion into horizontal shaft",
      "Stitch types and their classification",
      "Garment replication techniques",
      "Rating of patterns in relation to design",
      "Interlining & Interfacing"
    ],
    technicalSamples: []
  },
  {
    id: 7,
    courseType: "SHORT COURSE",
    certificateType: "SKILLS PROGRAMME CERTIFICATE",
    certificateName:
      "SKILLS PROGRAMME CERTIFICATE: ADVANCED GARMENT CONSTRUCTION AND TECHNOLOGY",
    duration: "12 weeks",
    fees: "R3 800 ( incl. reg fees of R1 900)",
    discountInfo: "",
    times: "Saturdays only 8am-12pm | 12pm-4pm",
    curriculum: [
      "Machine theory",
      "Terminology and visual knowledge of threading a single needle lockstitch machine and or over locker (demonstration by mentor)",
      "General rules for machine care",
      "Variants of machines in the industry and sewing equipment and attachments used for this program",
      "Stitch types",
      "Definition and relevance to the apparel industry",
      "Classification of Stitches",
      "Seams",
      "Definition and purpose",
      "Procedure and variations of seams",
      "Techniques (Demonstration by mentor)",
      "Interlining, lining, facings",
      "Technical sampling and Seam samples",
      "Closure samples and Variations of hemming",
      "Theory and Thread Path",
      "Procedures and functions of pressing",
      "Garment replication exercises",
      "Placing, rating and cutting of fabric correctly",
      "Bodice with a single style incorporated",
      "Skirt with functional pockets and closure",
      "Dress with darts and short sleeves",
      "Rating, Placing, Cutting, Quality and Labelling",
      "Production Theory such as commonly used machinery in apparel production",
      "Systematically know the correct method of needle thread path on a single lock stitch machine with sound knowledge on bobbin case bobbin winding, threading and insertion into horizontal shaft",
      "Stitch types and their classification",
      "Garment replication techniques",
      "Rating of patterns in relation to design",
      "Interlining & Interfacing"
    ],
    technicalSamples: [
      "(Collars) shirt collar/ Roll collar/ Collar with lapel",
      "Pocket (in seam pocket, Below patch pocket",
      "Pleats",
      "Variations of Closures and hems",
      "Minimum of 3 garments",
      "Fabric manipulation techniques such as pleats and tucks",
      "Sleeve variations",
      "Styled panel line"
    ]
  },
  {
    id: 8,
    courseType: "SHORT COURSE",
    certificateType: "SKILLS PROGRAMME CERTIFICATE",
    certificateName:
      "SKILLS PROGRAMME CERTIFICATE :BRIDAL PATTERN TECHNOLOGY",
    duration: "12 weeks",
    fees: "R3 800 ( incl. reg fees of R1 900)",
    discountInfo: "",
    times: "Saturdays only 8am-12pm | 12pm-4pm",
    curriculum: [
      "Bridal Pattern Theory: Definition and Terminology",
      "Brief History and principles of pattern design in bridal",
      "Textiles (Authentic and Synthetics in relation to grain variation)",
      "Figure Assessment and Measurements",
      "Tools Pattern Design Equipment",
      "Importance of a grain and identifying the grain on fabric and Analysis of silhouettes",
      "Factors such as fabric quality, shape and line",
      "Bridal Garment finishing’s, facings, linings and interlinings",
      "Dart positionings, style lines and variations",
      "Implementation of calculations for Basic Blocks into corset blocks",
      "Half Scale Blocks and Seam allowance variations and functions",
      "Placing and rating of fabric, Marking of pattern pieces",
      "Pinning and cutting of fabric and Basic pockets",
      "Female Block drafting for the Corset styles, various Bridal Skirts, Wedding Dress and finishes"
    ],
    technicalSamples: []
  },

  {
    id: 9,
    courseType: "SHORT COURSE",
    certificateType: "SKILLS PROGRAMME CERTIFICATE",
    certificateName:
      "SKILLS PROGRAMME CERTIFICATE: BRIDAL GARMENT CONSTRUCTION AND TECHNOLOGY",
    duration: "12 weeks",
    fees: "R3 800 ( incl. reg fees of R1 900)",
    discountInfo: "",
    times: "Saturdays only 8am-12pm | 12pm-4pm",
    curriculum: [
      "Machine theory",
      "Terminology and visual knowledge of threading a single needle lockstitch machine and or over locker (demonstration by mentor)",
      "General rules for machine care",
      "Variants of machines in the industry and sewing equipment and attachments used for this program",
      "Stitch types",
      "Definition and relevance to the apparel industry",
      "Classification of Stitches",
      "Seams",
      "Definition and purpose",
      "Procedure and variations of seams",
      "Techniques (Demonstration by mentor)",
      "Interlining, lining, facings",
      "Technical sampling and Seam samples",
      "Closure samples and Variations of hemming",
      "Procedures and functions of pressing",
      "Garment replication exercises",
      "Placing, rating and cutting of fabric correctly",
      "Bodice with a single style incorporated",
      "Skirt with functional pockets and closure",
      "Dress with darts and short sleeves",
      "Rating, Placing, Cutting, Quality and Labelling",
      "Production Theory such as commonly used machinery in Bridal construction",
      "Systematically know the correct method of needle thread path on a single lock stitch machine with sound knowledge on bobbin case bobbin winding, threading and insertion into horizontal shaft.",
      "Stitch types and their classification",
      "Garment replication techniques",
      "Rating of patterns in relation to design",
      "Theory and Thread Path",
      "Interlining & Interfacing"
    ],
    technicalSamples: [
      "Various Bridal Gowns, Evening, Resort and Cocktail suitable to current trend.",
      "Variations of Closures and hems",
      "Minimum of 3 garments",
      "Fabric manipulation techniques such as pleats and tucks.",
      "Styled panel lines"
    ]
  }
];

export const detailCourse = 
{
  id: 9,
  courseType: "SHORT COURSE",
  certificateType: "SKILLS PROGRAMME CERTIFICATE",
  certificateName:
    "SKILLS PROGRAMME CERTIFICATE: BRIDAL GARMENT CONSTRUCTION AND TECHNOLOGY",
  duration: "12 weeks",
  fees: "R3 800 ( incl. reg fees of R1 900)",
  discountInfo: "",
  times: "Saturdays only 8am-12pm | 12pm-4pm",
  curriculum: [
    "Machine theory",
    "Terminology and visual knowledge of threading a single needle lockstitch machine and or over locker (demonstration by mentor)",
    "General rules for machine care",
    "Variants of machines in the industry and sewing equipment and attachments used for this program",
    "Stitch types",
    "Definition and relevance to the apparel industry",
    "Classification of Stitches",
    "Seams",
    "Definition and purpose",
    "Procedure and variations of seams",
    "Techniques (Demonstration by mentor)",
    "Interlining, lining, facings",
    "Technical sampling and Seam samples",
    "Closure samples and Variations of hemming",
    "Procedures and functions of pressing",
    "Garment replication exercises",
    "Placing, rating and cutting of fabric correctly",
    "Bodice with a single style incorporated",
    "Skirt with functional pockets and closure",
    "Dress with darts and short sleeves",
    "Rating, Placing, Cutting, Quality and Labelling",
    "Production Theory such as commonly used machinery in Bridal construction",
    "Systematically know the correct method of needle thread path on a single lock stitch machine with sound knowledge on bobbin case bobbin winding, threading and insertion into horizontal shaft.",
    "Stitch types and their classification",
    "Garment replication techniques",
    "Rating of patterns in relation to design",
    "Theory and Thread Path",
    "Interlining & Interfacing"
  ],
  technicalSamples: [
    "Various Bridal Gowns, Evening, Resort and Cocktail suitable to current trend.",
    "Variations of Closures and hems",
    "Minimum of 3 garments",
    "Fabric manipulation techniques such as pleats and tucks.",
    "Styled panel lines"
  ]
};